[tool.poetry]
name = "pypo"
version = "0.1.0"
description = ""
authors = ["Ben-Hu <benjqh@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.5"
numpy = "^1.19.2"
pandas = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
